version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "7489:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: my_database
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
